from enum import Enum
from datetime import date, datetime
from typing import List, Optional

class EventType(Enum):
    MARKET = 'MARKET'
    SIGNAL = 'SIGNAL'
    ORDER = 'ORDER'
    FILL = 'FILL'
    MARGIN_CALL = 'MARGIN_CALL'

class Event:
    def __init__(self, event_type: EventType):
        self.event_type = event_type
    
class MarketEvent(Event):
    """
    Market event: new bar data arrived
    """
    def __init__(self, datetime: datetime, symbols: List[str]):
        super().__init__(EventType.MARKET)
        self.datetime = datetime
        self.symbols = symbols


class SignalEvent(Event):
    """
    Signal Event: signal generated by trading strategy

    Attributes:
        symbol: trading instrument
        datetime: time of signal generated
        signal_type: 'LONG', 'SHORT' OR 'EXIT'
        strength: signal strength (optional, use for managing position)
        confidence: signal confidence in [0.0, 1.0], used by PositionSizer to scale position
        expiry: optional datetime after which the signal is considered stale
    """
    def __init__(self, symbol: str, datetime: datetime, signal_type: str,
                 strength: float = 1.0, confidence: float = 1.0,
                 expiry: Optional[datetime] = None):
        super().__init__(EventType.SIGNAL)
        self.symbol = symbol
        self.datetime = datetime
        self.signal_type = signal_type
        self.strength = strength
        self.confidence = confidence
        self.expiry = expiry

    def is_expired(self, current_time: datetime) -> bool:
        if self.expiry is None:
            return False
        return current_time > self.expiry

class OrderEvent(Event):
    """
    Order Event: order generated by Portfolio

    Attributes:
        symbol: trading instrument
        order_type: 'MARKET' (supporting market order only)
        quantity: positive=buy, negative=sell
        direction: 'BUY' or 'SELL'
    """
    def __init__(self, symbol: str, quantity: int, direction: str, datetime: datetime, limit_price: Optional[float] = None, order_type: str = 'MARKET'):
        super().__init__(EventType.ORDER)
        self.symbol = symbol
        self.quantity = quantity
        self.direction = direction
        self.order_type = order_type
        self.datetime = datetime
        self.limit_price = limit_price

class FillEvent(Event):
    """
    Fill event: order fully executed

    Attributes:
        symbol: trading instrument
        exchange: exchange ('STOCK' or 'CRYPTO')
        quantity: traded quantity
        direction: 'BUY' or 'SELL'
        fill_price: traded price
        commission: commission
    """
    def __init__(self, symbol: str, exchange: str, quantity: int, direction: str, fill_price: float, datetime: datetime, rejected: bool, commission: float = 0.0):
        super().__init__(EventType.FILL)
        self.symbol = symbol
        self.exchange = exchange
        self.quantity = quantity
        self.direction = direction
        self.fill_price = fill_price
        self.commission = commission
        self.datetime = datetime
        self.rejected = rejected

class MarginCallEvent(Event):
    pass